# Generated by Django 5.1 on 2024-11-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Entite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("filiere", models.CharField(max_length=100)),
                ("anne_etude", models.CharField(max_length=10)),
                ("effectif", models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name="Filiere",
        ),
    ]
