# Generated by Django 5.1 on 2024-11-01 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0002_entite_delete_filiere"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_attribution", models.DateTimeField(auto_now_add=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[("actif", "Actif"), ("archive", "Archivé")],
                        default="actif",
                        max_length=50,
                    ),
                ),
                (
                    "entite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributions",
                        to="gestion.entite",
                    ),
                ),
                (
                    "salle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributions",
                        to="gestion.salle",
                    ),
                ),
            ],
            options={
                "ordering": ["date_attribution"],
                "unique_together": {("entite", "salle")},
            },
        ),
    ]
