# Generated by Django 5.1 on 2024-11-02 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0003_attribution"),
    ]

    operations = [
        migrations.AddField(
            model_name="entite",
            name="heure_debut",
            field=models.TimeField(default="00:00"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="entite",
            name="heure_fin",
            field=models.TimeField(default="00:00"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="entite",
            name="priorite",
            field=models.IntegerField(default=1),
        ),
    ]
